// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkefkrohopyttkyzjywk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZWZrcm9ob3B5dHRreXpqeXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTc1OTksImV4cCI6MjA2Nzc5MzU5OX0.jwT8CqgpW7oAw4umpfTGtVezmk3MwVcm_LLPU7k1780";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});